import { useCallback, useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, BadgeCheck, Bell, BriefcaseBusiness, ChevronRight, CircleDollarSign, ClipboardCheck, FileCheck2, Landmark, LogOut, MoreVertical, RefreshCw, Search, ShieldCheck, Sparkles, Users } from 'lucide-react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import './reference.css';
import { adminAuth } from './cognito';

type RecordItem = Record<string, unknown>;
type Page = 'overview' | 'users' | 'gigs' | 'payments' | 'identity' | 'skills' | 'proof' | 'trust' | 'disputes';
const API_URL = (import.meta.env.VITE_API_URL || '').replace(/\/$/, '');
const pageMeta: { id: Page; label: string; icon: typeof Activity; endpoint: string }[] = [
  { id: 'overview', label: 'Overview', icon: Activity, endpoint: '' }, { id: 'identity', label: 'Identity reviews', icon: BadgeCheck, endpoint: '/v1/admin/identity-reviews' }, { id: 'skills', label: 'Skill reviews', icon: ClipboardCheck, endpoint: '/v1/admin/skill-reviews' }, { id: 'proof', label: 'Proof review', icon: FileCheck2, endpoint: '/v1/admin/proof-review-queue' }, { id: 'trust', label: 'Trust cases', icon: ShieldCheck, endpoint: '/v1/admin/trust-cases' }, { id: 'disputes', label: 'Disputes', icon: AlertTriangle, endpoint: '/v1/admin/disputes' }, { id: 'users', label: 'Members', icon: Users, endpoint: '/v1/admin/users' }, { id: 'gigs', label: 'Gigs', icon: BriefcaseBusiness, endpoint: '/v1/admin/gigs' }, { id: 'payments', label: 'Payments', icon: CircleDollarSign, endpoint: '/v1/admin/payments' },
];
const getItems = (data: unknown): RecordItem[] => Array.isArray(data) ? data as RecordItem[] : data && typeof data === 'object' && Array.isArray((data as Record<string, unknown>).items) ? (data as Record<string, unknown>).items as RecordItem[] : [];
const text = (value: unknown) => value === null || value === undefined || value === '' ? '—' : typeof value === 'object' ? JSON.stringify(value) : String(value);
const formatTime = (value: unknown) => { if (!value) return '—'; const date = new Date(String(value)); return Number.isNaN(date.valueOf()) ? text(value) : date.toLocaleString(); };

function App() {
  const [token, setToken] = useState(''); const [email, setEmail] = useState(''); const [code, setCode] = useState(''); const [challenge, setChallenge] = useState(''); const [authBusy, setAuthBusy] = useState(false); const [page, setPage] = useState<Page>('overview'); const [data, setData] = useState<RecordItem[] | null>(null); const [summary, setSummary] = useState<RecordItem | null>(null); const [activity, setActivity] = useState<RecordItem[]>([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [lastUpdated, setLastUpdated] = useState<Date | null>(null);
  const request = useCallback(async (path: string, init: RequestInit = {}) => { if (!API_URL) throw new Error('VITE_API_URL is not configured. Add it in Netlify or .env.'); const response = await fetch(`${API_URL}${path}`, { ...init, headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', ...init.headers } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error((body as Record<string, string>).code || (body as Record<string, string>).message || `Request failed (${response.status})`); return body; }, [token]);
  const load = useCallback(async () => { if (!token) return; setLoading(true); setError(''); try { if (page === 'overview') { const [summaryData, activityData] = await Promise.all([request('/v1/admin/dashboard/summary'), request('/v1/admin/dashboard/activity?limit=12')]); setSummary(summaryData as RecordItem); setActivity(getItems(activityData)); setData(null); } else { const selected = pageMeta.find((item) => item.id === page)!; const suffix = page === 'users' && search.trim() ? `?query=${encodeURIComponent(search.trim())}` : ''; setData(getItems(await request(`${selected.endpoint}${suffix}`))); } setLastUpdated(new Date()); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load data.'); } finally { setLoading(false); } }, [page, request, search, token]);
  useEffect(() => { void load(); }, [load]);
  const completeReview = useCallback(async (item: RecordItem, action: 'approve' | 'reject') => { const reviewId = String(item.reviewId || ''); if (!reviewId || !['identity', 'skills'].includes(page) || !window.confirm(`Are you sure you want to ${action} review ${reviewId}? This action is audit logged.`)) return; try { setLoading(true); setError(''); const prefix = page === 'identity' ? 'identity-reviews' : 'skill-reviews'; await request(`/v1/admin/${prefix}/${encodeURIComponent(reviewId)}/${action}`, { method: 'POST', body: JSON.stringify({ confirmation: `${action.toUpperCase()}:${reviewId}` }) }); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not complete the review.'); } finally { setLoading(false); } }, [load, page, request]);
  const queues = useMemo(() => Object.entries((summary?.queues as Record<string, unknown>) || {}), [summary]); const openTasks = queues.reduce((total, [, value]) => total + (Number(value) || 0), 0); const currentMeta = pageMeta.find((item) => item.id === page)!;
  if (!token) { const begin = async () => { try { setAuthBusy(true); setError(''); setChallenge(await adminAuth.beginOtp(email.trim().toLowerCase())); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to start sign-in.'); } finally { setAuthBusy(false); } }; const verify = async () => { try { setAuthBusy(true); setError(''); setToken(await adminAuth.verifyOtp(email.trim().toLowerCase(), challenge, code)); } catch (caught) { setError(caught instanceof Error ? caught.message : 'The code was not accepted.'); } finally { setAuthBusy(false); } }; return <main className="sign-in"><section className="sign-in-card"><div className="brand-mark">V</div><p className="eyebrow">VOWCH OPERATIONS</p><h1>Admin portal</h1><p className="muted">Authorised operators sign in with a short-lived email code. Administrator access is enforced by the backend.</p><label>Work email<input disabled={Boolean(challenge)} type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="operator@example.com" /></label>{challenge && <label>6-digit code<input value={code} maxLength={6} inputMode="numeric" onChange={(event) => setCode(event.target.value.replace(/\D/g, ''))} placeholder="123456" autoFocus /></label>}<button disabled={authBusy || !email || (challenge ? code.length !== 6 : false)} onClick={() => void (challenge ? verify() : begin())}>{authBusy ? 'Please wait…' : challenge ? 'Open operations portal' : 'Send secure email code'} <ChevronRight size={17} /></button>{challenge && <button className="quiet-button" onClick={() => { setChallenge(''); setCode(''); }}>Use another email</button>}<p className="hint">The access token stays only in this browser tab. It is never saved by Vowch.</p>{error && <p className="error">{error}</p>}{(!API_URL || !adminAuth.configured) && <p className="error">Missing deployment configuration.</p>}</section></main>; }
  return <main className="shell"><aside><div className="logo"><div className="brand-mark">V</div><span>VOWCH <small>OPS</small></span></div><nav>{pageMeta.map(({ id, label, icon: Icon }) => <button key={id} className={page === id ? 'active' : ''} onClick={() => { setPage(id); setSearch(''); }}><Icon size={16} />{label}</button>)}</nav><div className="side-insight"><Sparkles size={17} /><p>Trust signals are monitored in real time.</p><button onClick={() => setPage('trust')}>VIEW TRUST CASES <ChevronRight size={13} /></button></div><button className="sign-out" onClick={() => { setToken(''); setEmail(''); setCode(''); setChallenge(''); }}><LogOut size={16} />Sign out</button></aside><section className="content"><header><div><p className="eyebrow">VOWCH ADMIN / LIVE OPERATIONS</p><h1>{page === 'overview' ? 'Hello, Operator' : currentMeta.label}</h1><p className="subheading">{page === 'overview' ? 'Your trust and marketplace pulse, in one place.' : 'Review, audit, and resolve operational work.'}</p></div><div className="header-actions">{lastUpdated && <span className="updated">Updated {lastUpdated.toLocaleTimeString()}</span>}<button className="icon-button" onClick={() => void load()} disabled={loading} title="Refresh"><RefreshCw size={18} className={loading ? 'spinning' : ''} /></button><button className="icon-button" title="Notifications"><Bell size={18} /></button></div></header>{error && <div className="error-banner"><AlertTriangle size={18} /><span>{error}</span></div>}{page === 'overview' ? <Overview queues={queues} activity={activity} openTasks={openTasks} /> : <section className="panel"><div className="panel-heading"><div><p className="eyebrow">OPERATIONS QUEUE</p><h2>{currentMeta.label}</h2></div>{page === 'users' && <form onSubmit={(event) => { event.preventDefault(); void load(); }} className="search"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Find a member" /><button>Search</button></form>}</div><ActivityTable items={data || []} reviewActions={page === 'identity' || page === 'skills' ? completeReview : undefined} /></section>}</section></main>;
}

function Overview({ queues, activity, openTasks }: { queues: [string, unknown][]; activity: RecordItem[]; openTasks: number }) { return <><section className="overview-grid"><article className="trust-card"><div className="card-top"><p className="eyebrow">TRUST NETWORK</p><MoreVertical size={19} /></div><div className="trust-ring"><span /><span /><span /><strong>{openTasks}</strong><small>OPEN TASKS</small></div><div className="legend"><span><i className="mint" />IDENTITY</span><span><i className="lime" />SKILLS</span><span><i className="rose" />TRUST</span></div></article><article className="queue-hero"><div className="card-top"><div><p className="eyebrow">OPERATIONS QUEUE</p><h2>Actionable work</h2></div><strong>{openTasks}</strong></div><div className="queue-line"><span style={{ width: `${Math.min(100, openTasks * 8)}%` }} /></div><div className="queue-key"><span>0%</span><span>LIVE PRIORITY</span><span>100%</span></div><div className="queue-list">{queues.slice(0, 4).map(([name, value]) => <div key={name}><span>{name.replace(/([A-Z])/g, ' $1')}</span><b>{text(value)}</b></div>)}{!queues.length && <p className="empty-copy">Queues will appear after the first successful API refresh.</p>}</div></article><article className="signal-card"><Sparkles size={22} /><p>Vowch protects every exchange with auditable trust signals.</p><button>TRUST HEALTH <ChevronRight size={15} /></button></article></section><section className="metric-row">{queues.map(([name, value], index) => <article key={name} className={`metric-card metric-${index % 4}`}><p>{name.replace(/([A-Z])/g, ' $1')}</p><strong>{text(value)}</strong><span>{index % 2 ? 'NEEDS REVIEW' : 'LIVE QUEUE'}</span></article>)}</section><section className="panel activity-panel"><div className="panel-heading"><div><p className="eyebrow">LATEST EVENTS</p><h2>Recent operations activity</h2><p>Immutable audit history from the Vowch backend.</p></div><button className="quiet-button">VIEW AUDIT LOG <ChevronRight size={15} /></button></div><ActivityTable items={activity} /></section></> }
function ActivityTable({ items, reviewActions }: { items: RecordItem[]; reviewActions?: (item: RecordItem, action: 'approve' | 'reject') => void }) { const keys = useMemo(() => [...new Set(items.flatMap((item) => Object.keys(item)))].filter((key) => !['pk', 'sk', 'gsi1pk', 'gsi1sk', 'gsi2pk', 'gsi2sk', 'gsi3pk', 'gsi3sk', 'gsi4pk', 'gsi4sk'].includes(key)).slice(0, 6), [items]); if (!items.length) return <div className="empty"><Landmark size={26} /><h3>No records found</h3><p>The queue is currently clear, or your admin role does not have permission to view it.</p></div>; return <div className="table-wrap"><table><thead><tr>{keys.map((key) => <th key={key}>{key.replace(/([A-Z])/g, ' $1')}</th>)}{reviewActions && <th>Decision</th>}</tr></thead><tbody>{items.map((item, index) => <tr key={String(item.id || item.userId || item.gigId || item.paymentId || item.reviewId || item.caseId || index)}>{keys.map((key) => <td key={key} title={text(item[key])}>{/At$|Time$|created|updated/i.test(key) ? formatTime(item[key]) : text(item[key])}</td>)}{reviewActions && <td className="decisions"><button className="approve" onClick={() => reviewActions(item, 'approve')}>Approve</button><button className="reject" onClick={() => reviewActions(item, 'reject')}>Reject</button></td>}</tr>)}</tbody></table></div>; }
createRoot(document.getElementById('root')!).render(<App />);
