import { useCallback, useEffect, useMemo, useState } from 'react';
import { Bell, BriefcaseBusiness, ChevronRight, CircleDollarSign, Compass, House, LogOut, Menu, MessageCircle, Plus, Search, Send, ShieldCheck, Sparkles, UserRound, WalletCards, X } from 'lucide-react';
import { createRoot } from 'react-dom/client';
import { createApi, type ApiGig, type Profile } from './api';
import { cognitoAuth } from './cognito';
import './styles.css';

type Tab = 'discover' | 'post' | 'jobs' | 'messages' | 'passport' | 'house' | 'wallet' | 'settings';
type Session = { accessToken: string; email: string };
type Workspace = { profile: Profile | null; gigs: ApiGig[]; applications: Record<string, unknown>[]; workerGigs: ApiGig[]; earnings: Record<string, unknown>; poster: Record<string, unknown>; passports: Record<string, unknown>[]; notifications: Record<string, unknown>[]; communities: Record<string, unknown>[]; house: Record<string, unknown> };
const nav: { id: Tab; label: string; icon: typeof Compass }[] = [
  { id: 'discover', label: 'Discover', icon: Compass }, { id: 'post', label: 'Post a gig', icon: Plus }, { id: 'jobs', label: 'My jobs', icon: BriefcaseBusiness }, { id: 'messages', label: 'Messages', icon: MessageCircle }, { id: 'passport', label: 'My passport', icon: ShieldCheck }, { id: 'house', label: 'My House', icon: House }, { id: 'wallet', label: 'Wallet', icon: WalletCards }, { id: 'settings', label: 'Settings', icon: UserRound },
];
const emptyWorkspace: Workspace = { profile: null, gigs: [], applications: [], workerGigs: [], earnings: {}, poster: {}, passports: [], notifications: [], communities: [], house: {} };
const money = (value: unknown) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format((Number(value) || 0) / 100);
const label = (value: unknown) => String(value || '').replace(/([A-Z])/g, ' $1').replace(/_/g, ' ');
const initials = (name?: string) => (name || 'Vowch').split(' ').map((word) => word[0]).join('').slice(0, 2).toUpperCase();

function App() {
  const [session, setSession] = useState<Session | null>(() => { try { return JSON.parse(sessionStorage.getItem('vowch-session') || 'null'); } catch { return null; } });
  if (!session) return <Auth onAuthenticated={(next) => { sessionStorage.setItem('vowch-session', JSON.stringify(next)); setSession(next); }} />;
  return <WorkspaceApp session={session} signOut={() => { sessionStorage.removeItem('vowch-session'); setSession(null); }} />;
}

function Auth({ onAuthenticated }: { onAuthenticated: (session: Session) => void }) {
  const [stage, setStage] = useState<'email' | 'confirm' | 'otp'>('email'); const [email, setEmail] = useState(''); const [code, setCode] = useState(''); const [challenge, setChallenge] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const start = async () => { setBusy(true); setError(''); try { const result = await cognitoAuth.register(email.trim().toLowerCase()); if (result.existing) { const otp = await cognitoAuth.beginOtp(email.trim().toLowerCase()); setChallenge(otp); setStage('otp'); } else setStage('confirm'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to start sign-in.'); } finally { setBusy(false); } };
  const confirm = async () => { setBusy(true); setError(''); try { await cognitoAuth.confirm(email.trim().toLowerCase(), code); const otp = await cognitoAuth.beginOtp(email.trim().toLowerCase()); setChallenge(otp); setCode(''); setStage('otp'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Confirmation failed.'); } finally { setBusy(false); } };
  const verify = async () => { setBusy(true); setError(''); try { const result = await cognitoAuth.answerOtp(email.trim().toLowerCase(), challenge, code); onAuthenticated({ accessToken: result.accessToken, email }); } catch (caught) { setError(caught instanceof Error ? caught.message : 'That code did not work.'); } finally { setBusy(false); } };
  const action = stage === 'email' ? start : stage === 'confirm' ? confirm : verify;
  return <main className="auth-page"><section className="auth-art"><div className="brand"><i>v</i> vowch</div><p className="eyebrow">TRUSTED WORK, HUMANLY VERIFIED</p><h1>A better way to get things <em>done.</em></h1><p>Browse work, build your trust passport, and exchange value with people who can vouch for one another.</p><div className="auth-orbit"><span>trust</span><span>work</span><span>community</span></div></section><section className="auth-form"><div><p className="eyebrow">WELCOME TO VOWCH</p><h2>{stage === 'email' ? 'Start with your email' : stage === 'confirm' ? 'Confirm your email' : 'Check your inbox'}</h2><p className="muted">{stage === 'email' ? 'We use a short email code instead of passwords.' : stage === 'confirm' ? `Enter the confirmation code sent to ${email}.` : `Enter the 6-digit sign-in code sent to ${email}.`}</p></div><label>Email address<input disabled={stage !== 'email'} type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@example.com" autoComplete="email" /></label>{stage !== 'email' && <label>Code<input inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, ''))} placeholder="123456" autoFocus /></label>}<button className="primary" disabled={busy || !email || (stage !== 'email' && code.length !== 6)} onClick={() => void action()}>{busy ? 'Please wait…' : stage === 'email' ? 'Continue with email' : stage === 'confirm' ? 'Confirm email' : 'Sign in securely'} <ChevronRight size={17} /></button>{stage === 'otp' && <button className="text-button" disabled={busy} onClick={() => void (async () => { try { setBusy(true); const otp = await cognitoAuth.beginOtp(email); setChallenge(otp); setCode(''); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not resend code.'); } finally { setBusy(false); } })()}>Send another code</button>}{stage !== 'email' && <button className="text-button" onClick={() => { setStage('email'); setCode(''); setError(''); }}>Use another email</button>}{error && <p className="error">{error}</p>}{!cognitoAuth.configured && <p className="error">Authentication is not configured for this deployment.</p>}</section></main>;
}

function WorkspaceApp({ session, signOut }: { session: Session; signOut: () => void }) {
  const api = useMemo(() => createApi(session.accessToken), [session.accessToken]); const [tab, setTab] = useState<Tab>('discover'); const [data, setData] = useState<Workspace>(emptyWorkspace); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [menu, setMenu] = useState(false); const [selected, setSelected] = useState<ApiGig | null>(null); const [refresh, setRefresh] = useState(0);
  const load = useCallback(async () => { setLoading(true); setError(''); const calls = await Promise.allSettled([api.me(), api.gigs(), api.applications(), api.workerGigs(), api.earnings(), api.poster(), api.passports(), api.notifications(), api.communities(), api.houseStats()]); const values = calls.map((call) => call.status === 'fulfilled' ? call.value : null); const failure = calls.find((call) => call.status === 'rejected') as PromiseRejectedResult | undefined; const applications = values[2] as { items?: Record<string, unknown>[] } | null; const earnings = values[4] as { items?: Record<string, unknown>[]; totalReleasedPaise?: number } | null; const poster = values[5] as { poster?: Record<string, unknown>; gigs?: ApiGig[]; counts?: Record<string, number> } | null; const notices = values[7] as { items?: Record<string, unknown>[] } | null; setData({ profile: values[0] as Profile | null, gigs: (values[1] as ApiGig[] | null) || [], applications: applications?.items || [], workerGigs: (values[3] as ApiGig[] | null) || [], earnings: { totalReleasedPaise: earnings?.totalReleasedPaise || 0, items: earnings?.items || [] }, poster: { ...(poster?.poster || {}), ...(poster?.counts || {}), gigs: poster?.gigs || [] }, passports: (values[6] as Record<string, unknown>[] | null) || [], notifications: notices?.items || [], communities: (values[8] as Record<string, unknown>[] | null) || [], house: (values[9] as Record<string, unknown> | null) || {} }); if (failure) setError(failure.reason instanceof Error ? failure.reason.message : 'Some workspace data could not load.'); setLoading(false); }, [api]);
  useEffect(() => { void load(); }, [load, refresh]);
  if (data.profile && !data.profile.onboardingComplete) return <Onboarding api={api} profile={data.profile} reload={() => setRefresh((value) => value + 1)} signOut={signOut} />;
  const memberName = data.profile?.displayName || session.email.split('@')[0];
  return <div className="app-shell"><aside className={menu ? 'open' : ''}><div className="brand"><i>v</i> vowch</div><p className="side-caption">YOUR TRUSTED WORKSPACE</p><nav>{nav.map(({ id, label: navLabel, icon: Icon }) => <button key={id} className={tab === id ? 'active' : ''} onClick={() => { setTab(id); setMenu(false); }}><Icon size={18} />{navLabel}</button>)}</nav><div className="house-card"><House size={18} /><p><b>{String(data.house.name || 'Your House')}</b><br />Your community trust network</p><span>{Number(data.house.memberCount || data.house.members || 0)} members</span><button onClick={() => setTab('house')}>Open House <ChevronRight size={14} /></button></div><div className="user-chip"><div className="avatar coral">{initials(memberName)}</div><span><b>{memberName}</b><small>{data.profile?.verificationStatus || 'Member'}</small></span></div></aside><main><header className="topbar"><button className="mobile-menu" onClick={() => setMenu(!menu)}><Menu size={20} /></button><div><p className="eyebrow">VOWCH MEMBER PORTAL</p><b>{loading ? 'Syncing your workspace…' : 'Your community, in one place'}</b></div><div className="top-actions"><button onClick={() => setTab('messages')}><Bell size={18} /><i /></button><button className="profile-button" onClick={() => setTab('settings')}><div className="avatar coral">{initials(memberName)}</div><span>{memberName}</span></button></div></header>{error && <div className="error-banner">{error}<button onClick={() => setRefresh((value) => value + 1)}>Retry</button></div>}{tab === 'discover' && <Discover gigs={data.gigs} select={setSelected} />}{tab === 'post' && <PostGig api={api} done={() => { setRefresh((value) => value + 1); setTab('jobs'); }} />}{tab === 'jobs' && <Jobs data={data} select={setSelected} />}{tab === 'messages' && <Messages api={api} notifications={data.notifications} gigs={[...data.gigs, ...data.workerGigs]} />}{tab === 'passport' && <Passport profile={data.profile} passports={data.passports} />}{tab === 'house' && <HouseView house={data.house} communities={data.communities} />}{tab === 'wallet' && <Wallet earnings={data.earnings} />}{tab === 'settings' && <Settings api={api} profile={data.profile} signOut={signOut} reload={() => setRefresh((value) => value + 1)} />}</main>{selected && <GigModal api={api} gig={selected} close={() => setSelected(null)} applied={() => { setSelected(null); setRefresh((value) => value + 1); }} />}</div>;
}

function Onboarding({ api, profile, reload, signOut }: { api: ReturnType<typeof createApi>; profile: Profile; reload: () => void; signOut: () => void }) { const [displayName, setDisplayName] = useState(profile.displayName || ''); const [skill, setSkill] = useState(profile.primarySkill || ''); const [inviteCode, setInviteCode] = useState(''); const [reference, setReference] = useState(''); const [done, setDone] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await api.onboarding({ displayName, primarySkill: skill, inviteCode, identityReference: reference }); setDone(true); reload(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not submit onboarding.'); } finally { setBusy(false); } }; if (done) return <main className="onboarding-page"><section className="onboarding-card"><div className="brand-mark">v</div><p className="eyebrow">ONBOARDING RECEIVED</p><h1>Your trust passport is being reviewed.</h1><p>We have your details. You can sign back in once a community admin completes the verification queue.</p><button className="primary" onClick={signOut}>Return to sign in</button></section></main>; return <main className="onboarding-page"><section className="onboarding-card"><div className="brand-mark">v</div><p className="eyebrow">STEP 1 OF 1 · TRUST ONBOARDING</p><h1>Let your community know you.</h1><p className="muted">Vowch is invitation-based. A valid community invite is required to protect members and prevent marketplace spam.</p><form onSubmit={submit}><label>Your name<input value={displayName} onChange={(event) => setDisplayName(event.target.value)} required placeholder="How neighbours know you" /></label><label>Primary skill<input value={skill} onChange={(event) => setSkill(event.target.value)} required placeholder="e.g. Tutoring, design, pet care" /></label><label>Community invite code<input value={inviteCode} onChange={(event) => setInviteCode(event.target.value)} required placeholder="Provided by your House admin" /></label><label>Who referred you? <small>(optional)</small><input value={reference} onChange={(event) => setReference(event.target.value)} placeholder="Name or House" /></label><button className="primary" disabled={busy}>{busy ? 'Submitting…' : 'Submit for verification'} <ChevronRight size={17} /></button>{error && <p className="error">{error}</p>}</form><button className="text-button" onClick={signOut}>Sign out</button></section></main>; }

function Discover({ gigs, select }: { gigs: ApiGig[]; select: (gig: ApiGig) => void }) { const [search, setSearch] = useState(''); const filtered = gigs.filter((gig) => `${gig.title} ${gig.description} ${gig.skill || ''}`.toLowerCase().includes(search.toLowerCase())); return <section className="page"><div className="discover-head"><div><p className="eyebrow">LIVE MARKETPLACE</p><h1>Find work you can <em>vowch</em> for.</h1><p className="lede">Real opportunities from your trusted network, backed by clear status and auditable exchange.</p></div><div className="trust-score"><Sparkles size={19} /><span><b>Live</b> marketplace</span></div></div><div className="search-bar"><Search size={19} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search gigs, skills, or descriptions" /></div><div className="discover-tools"><span>{filtered.length} live gigs</span><span>Remote-first launch</span></div><div className="gig-grid">{filtered.map((gig) => <GigCard key={gig.gigId} gig={gig} select={select} />)}{!filtered.length && <Empty icon={<Compass size={27} />} copy="No live gigs match this search yet. Check back soon, or post a request." />}</div></section>; }
function GigCard({ gig, select }: { gig: ApiGig; select: (gig: ApiGig) => void }) { return <article className="gig-card"><div className="gig-art mint"><span>{gig.skill || 'Community work'}</span></div><div className="gig-body"><div className="gig-meta"><span>{gig.workMode || 'REMOTE'}</span><small>{gig.status || 'OPEN'}</small></div><h3>{gig.title}</h3><p>{gig.description || 'Details are shared with verified applicants.'}</p><div className="gig-place">Remote · {gig.skill || 'General'}</div><div className="gig-footer"><span><b>{money(gig.budgetPaise)}</b> fixed</span><button onClick={() => select(gig)}>View gig <ChevronRight size={15} /></button></div></div></article>; }
function PostGig({ api, done }: { api: ReturnType<typeof createApi>; done: () => void }) { const [title, setTitle] = useState(''); const [skill, setSkill] = useState(''); const [budget, setBudget] = useState(''); const [description, setDescription] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await api.createGig({ title, skill, budgetPaise: Math.round(Number(budget) * 100), description, workMode: 'REMOTE' }); done(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not create gig.'); } finally { setBusy(false); } }; return <section className="page form-page"><p className="eyebrow">POST A TRUSTED REQUEST</p><h1>What do you need help with?</h1><p className="lede">For the launch demo, gigs are remote-first. Created gigs enter the secure funding workflow before they are published.</p><form onSubmit={submit}><label>Gig title<input value={title} onChange={(event) => setTitle(event.target.value)} required placeholder="e.g. Help with a pitch deck" /></label><div className="form-row"><label>Skill needed<input value={skill} onChange={(event) => setSkill(event.target.value)} required placeholder="Design, writing, research…" /></label><label>Budget (USD)<input type="number" min="1" step="0.01" value={budget} onChange={(event) => setBudget(event.target.value)} required placeholder="50" /></label></div><label>Describe the task<textarea value={description} onChange={(event) => setDescription(event.target.value)} required rows={5} placeholder="What outcome do you need, and when?" /></label><button className="primary-submit" disabled={busy}>{busy ? 'Creating…' : 'Create secure gig'} <ChevronRight size={17} /></button>{error && <p className="error">{error}</p>}</form></section>; }
function Jobs({ data, select }: { data: Workspace; select: (gig: ApiGig) => void }) { return <section className="page"><p className="eyebrow">YOUR WORKSPACE</p><h1>Your gigs, clearly <em>tracked.</em></h1><div className="job-stats"><article><b>{data.applications.length}</b><span>Applications sent</span></article><article><b>{Number(data.poster.activeGigs || data.poster.openGigs || 0)}</b><span>Gigs posted</span></article><article><b>{money(data.earnings.availableCents || data.earnings.available || 0)}</b><span>Available earnings</span></article></div><div className="jobs-layout"><section className="job-panel"><div className="section-title"><h2>Work in progress</h2><span>Worker view</span></div>{data.workerGigs.length ? data.workerGigs.map((gig) => <div className="job-row" key={gig.gigId}><div className="job-icon mint"><BriefcaseBusiness size={18} /></div><div><b>{gig.title}</b><span>{gig.status || 'Active'}</span></div><button onClick={() => select(gig)}>View <ChevronRight size={15} /></button></div>) : <Empty icon={<BriefcaseBusiness size={27} />} copy="Apply to a gig and its status will appear here." />}</section><section className="job-panel"><div className="section-title"><h2>Applications</h2><span>{data.applications.length} sent</span></div>{data.applications.length ? data.applications.map((item, index) => <div className="job-row" key={String(item.applicationId || index)}><div className="job-icon peach"><Send size={18} /></div><div><b>{String(item.gigTitle || item.gigId || 'Gig application')}</b><span>{label(item.status || 'submitted')}</span></div></div>) : <Empty icon={<Send size={27} />} copy="Your submitted applications will appear here." />}</section></div></section>; }
function Messages({ api, notifications, gigs }: { api: ReturnType<typeof createApi>; notifications: Record<string, unknown>[]; gigs: ApiGig[] }) { const [gigId, setGigId] = useState(''); const [message, setMessage] = useState(''); const [result, setResult] = useState(''); const send = async () => { if (!gigId || !message.trim()) return; try { await api.sendMessage(gigId, message.trim()); setMessage(''); setResult('Message sent.'); } catch (caught) { setResult(caught instanceof Error ? caught.message : 'Unable to send message.'); } }; return <section className="page messages-page"><p className="eyebrow">YOUR INBOX</p><h1>Keep the work moving.</h1><div className="messages"><section>{notifications.length ? notifications.map((notice, index) => <div className="chat" key={String(notice.notificationId || index)}><div className="avatar lavender">V</div><span><b>{String(notice.title || 'Vowch update')}</b><small>{String(notice.message || notice.body || label(notice.type || 'notification'))}</small></span></div>) : <Empty icon={<Bell size={27} />} copy="No notifications yet." />}</section><section className="conversation"><div className="conversation-head"><b>Send a gig message</b><span>Live backend</span></div><label>Gig<select value={gigId} onChange={(event) => setGigId(event.target.value)}><option value="">Choose an active gig</option>{gigs.map((gig) => <option key={gig.gigId} value={gig.gigId}>{gig.title}</option>)}</select></label><div className="message-input"><input value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Write a message" /><button onClick={() => void send()}><Send size={17} /></button></div>{result && <p className="muted">{result}</p>}</section></div></section>; }
function Passport({ profile, passports }: { profile: Profile | null; passports: Record<string, unknown>[] }) { return <section className="page passport-page"><p className="eyebrow">YOUR VOWCH PASSPORT</p><h1>Trust that travels with you.</h1><div className="passport-card"><div className="passport-top"><div className="brand-mark">v</div><span>VOWCH PASSPORT<br /><small>{String(profile?.verificationStatus || 'VERIFICATION PENDING')}</small></span><ShieldCheck size={27} /></div><div className="passport-person"><div className="passport-avatar">{initials(profile?.displayName)}</div><div><h2>{profile?.displayName || 'Vowch member'}</h2><p>{profile?.primarySkill || 'Add your primary skill during onboarding'}</p></div><b>{String(profile?.tier || 'MEMBER')}</b></div><div className="passport-stats"><span><b>{Number(profile?.trustScore || 0)}</b> Trust score</span><span><b>{Number(profile?.vouchCount || 0)}</b> Vouches</span><span><b>{passports.length}</b> Credentials</span></div></div></section>; }
function HouseView({ house, communities }: { house: Record<string, unknown>; communities: Record<string, unknown>[] }) { return <section className="page"><p className="eyebrow">COMMUNITY TRUST</p><h1>Your House is your <em>network.</em></h1><div className="jobs-layout"><section className="job-panel"><h2>{String(house.name || 'Your House')}</h2><p className="lede">{Number(house.memberCount || house.members || 0)} members · {Number(house.activeGigs || 0)} active gigs</p><p className="muted">Houses connect people through local reputation, shared activity, and accountable recommendations.</p></section><section className="job-panel"><div className="section-title"><h2>Communities</h2><span>{communities.length}</span></div>{communities.length ? communities.map((item, index) => <div className="job-row" key={String(item.communityId || index)}><div className="job-icon gold"><House size={18} /></div><div><b>{String(item.name || item.communityId || 'Community')}</b><span>{label(item.status || 'active')}</span></div></div>) : <Empty icon={<House size={27} />} copy="No community memberships are available yet." />}</section></div></section>; }
function Wallet({ earnings }: { earnings: Record<string, unknown> }) { return <section className="page wallet-page"><p className="eyebrow">PAYMENTS & ESCROW</p><h1>Your work, paid <em>fairly.</em></h1><div className="balance-card"><span>AVAILABLE BALANCE</span><b>{money(earnings.availableCents || earnings.available || 0)}</b><p>Payments and release status are fetched directly from Vowch.</p><button>Withdrawals are managed by Vowch</button></div><section className="transactions"><div className="section-title"><h2>Earnings snapshot</h2><span>Live data</span></div>{Object.entries(earnings).filter(([, value]) => typeof value === 'number').map(([key, value]) => <div className="transaction" key={key}><div className="job-icon mint"><CircleDollarSign size={18} /></div><div><b>{label(key)}</b><span>Current account total</span></div><strong>{money(value)}</strong></div>) || <Empty icon={<CircleDollarSign size={27} />} copy="Your completed earnings will appear here." />}</section></section>; }
function Settings({ api, profile, signOut, reload }: { api: ReturnType<typeof createApi>; profile: Profile | null; signOut: () => void; reload: () => void }) { const [name, setName] = useState(profile?.displayName || ''); const [skill, setSkill] = useState(profile?.primarySkill || ''); const [note, setNote] = useState(''); const save = async (event: React.FormEvent) => { event.preventDefault(); try { await api.updateProfile({ displayName: name, primarySkill: skill }); setNote('Saved to your Vowch profile.'); reload(); } catch (caught) { setNote(caught instanceof Error ? caught.message : 'Could not save profile.'); } }; return <section className="page form-page"><p className="eyebrow">ACCOUNT SETTINGS</p><h1>Keep your details current.</h1><form onSubmit={save}><label>Display name<input value={name} onChange={(event) => setName(event.target.value)} /></label><label>Primary skill<input value={skill} onChange={(event) => setSkill(event.target.value)} /></label><button className="primary-submit">Save profile</button>{note && <p className="muted">{note}</p>}</form><button className="danger-button" onClick={signOut}><LogOut size={16} /> Sign out</button></section>; }
function GigModal({ api, gig, close, applied }: { api: ReturnType<typeof createApi>; gig: ApiGig; close: () => void; applied: () => void }) { const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const submit = async () => { setBusy(true); setError(''); try { await api.apply(gig.gigId, { proposal: message, proposedAmountPaise: gig.budgetPaise }); applied(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not submit application.'); } finally { setBusy(false); } }; return <div className="modal-backdrop" onMouseDown={close}><article className="gig-modal" onMouseDown={(event) => event.stopPropagation()}><button className="close" onClick={close}><X size={20} /></button><div className="modal-art mint"><span>{gig.skill || 'Community work'}</span></div><p className="eyebrow">{gig.workMode || 'REMOTE'} · {gig.status || 'OPEN'}</p><h2>{gig.title}</h2><p>{gig.description || 'Details are shared by the poster.'}</p><div className="modal-details"><span>Budget: {money(gig.budgetPaise)}</span><span>Skill: {gig.skill || 'General'}</span></div><label className="modal-label">Why are you a good fit?<textarea value={message} onChange={(event) => setMessage(event.target.value)} rows={3} placeholder="Introduce yourself briefly" /></label><div className="modal-footer"><b>{money(gig.budgetPaise)}</b><button disabled={busy} onClick={() => void submit()}>{busy ? 'Submitting…' : 'Apply to help'} <ChevronRight size={16} /></button></div>{error && <p className="error">{error}</p>}</article></div>; }
function Empty({ icon, copy }: { icon: React.ReactNode; copy: string }) { return <div className="blank">{icon}<p>{copy}</p></div>; }
createRoot(document.getElementById('root')!).render(<App />);
