import { useMemo, useState } from 'react';
import { Bell, BriefcaseBusiness, CheckCircle2, ChevronRight, CircleDollarSign, Compass, HeartHandshake, House, MapPin, Menu, MessageCircle, Plus, Search, Send, ShieldCheck, Sparkles, Star, UserRound, WalletCards, X } from 'lucide-react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type Tab = 'discover' | 'post' | 'jobs' | 'messages' | 'passport' | 'wallet';
type Gig = { id: string; title: string; description: string; skill: string; mode: string; area: string; budget: number; poster: string; vouches: number; posted: string; tone: string };
const demoGigs: Gig[] = [
  { id:'gig-1', title:'Need help moving a sofa', description:'A two-person carry from my apartment to the van. Saturday morning.', skill:'Moving help', mode:'ONSITE', area:'Williamsburg, Brooklyn', budget:40, poster:'Sofia J.', vouches:8, posted:'20m ago', tone:'peach' },
  { id:'gig-2', title:'Dog walker needed', description:'Walk Miso for 45 minutes this afternoon. Calm neighbourhood route.', skill:'Pet care', mode:'ONSITE', area:'Fort Greene, Brooklyn', budget:25, poster:'David Chen', vouches:15, posted:'1h ago', tone:'lavender' },
  { id:'gig-3', title:'Tutor for high school math', description:'Patient algebra tutor for two sessions this week.', skill:'Tutoring', mode:'REMOTE', area:'Remote', budget:50, poster:'Mina S.', vouches:12, posted:'2h ago', tone:'gold' },
  { id:'gig-4', title:'Plant care while I travel', description:'Water six happy houseplants and check the balcony herbs.', skill:'Home care', mode:'ONSITE', area:'Park Slope, Brooklyn', budget:30, poster:'Ishaan R.', vouches:10, posted:'3h ago', tone:'mint' },
];
const nav: { id: Tab; label: string; icon: typeof Compass }[] = [{id:'discover',label:'Discover',icon:Compass},{id:'post',label:'Post a gig',icon:Plus},{id:'jobs',label:'My jobs',icon:BriefcaseBusiness},{id:'messages',label:'Messages',icon:MessageCircle},{id:'passport',label:'My passport',icon:ShieldCheck},{id:'wallet',label:'Wallet',icon:WalletCards}];

function App() {
  const [tab,setTab] = useState<Tab>('discover'); const [search,setSearch] = useState(''); const [mode,setMode] = useState<'ALL'|'ONSITE'|'REMOTE'>('ALL'); const [selected,setSelected] = useState<Gig | null>(null); const [applied,setApplied] = useState<string[]>([]); const [menu,setMenu] = useState(false); const [created,setCreated] = useState<Gig[]>([]);
  const gigs = useMemo(() => [...created,...demoGigs].filter((gig) => (mode==='ALL'||gig.mode===mode) && `${gig.title} ${gig.skill} ${gig.area}`.toLowerCase().includes(search.toLowerCase())), [created,mode,search]);
  const apply = (gig: Gig) => { setApplied((current) => current.includes(gig.id) ? current : [...current,gig.id]); setSelected(null); setTab('jobs'); };
  const addGig = (gig: Gig) => { setCreated((current) => [gig,...current]); setTab('jobs'); };
  return <div className="app-shell"><aside className={menu?'open':''}><div className="brand"><div className="brand-dot">v</div><span>vowch</span></div><p className="side-caption">TRUSTED LOCAL WORK</p><nav>{nav.map(({id,label,icon:Icon}) => <button key={id} className={tab===id?'active':''} onClick={() => {setTab(id);setMenu(false)}}><Icon size={18}/>{label}</button>)}</nav><div className="house-card"><House size={18}/><p><b>Your House</b><br/>Brooklyn Makers</p><span>24 members</span><button onClick={() => setTab('passport')}>Open House <ChevronRight size={14}/></button></div><div className="user-chip"><div className="avatar coral">AR</div><span><b>Aria Rao</b><small>Gold Vowcher</small></span><ChevronRight size={16}/></div></aside><main><header className="topbar"><button className="mobile-menu" onClick={() => setMenu(!menu)}><Menu size={20}/></button><div className="location"><MapPin size={17}/><span>Brooklyn, NY</span><small>Change</small></div><div className="top-actions"><button><Bell size={18}/><i /></button><button className="profile-button"><div className="avatar coral">AR</div><span>Aria Rao</span></button></div></header>{tab==='discover' && <Discover gigs={gigs} search={search} setSearch={setSearch} mode={mode} setMode={setMode} select={setSelected} />}{tab==='post' && <PostGig submit={addGig}/>} {tab==='jobs' && <Jobs applied={applied} created={created} select={setSelected}/>} {tab==='messages' && <Messages/>} {tab==='passport' && <Passport/>} {tab==='wallet' && <Wallet/>}</main>{selected && <GigModal gig={selected} applied={applied.includes(selected.id)} close={() => setSelected(null)} apply={() => apply(selected)}/>}</div>;
}
function Discover({gigs,search,setSearch,mode,setMode,select}:{gigs:Gig[];search:string;setSearch:(value:string)=>void;mode:string;setMode:(value:'ALL'|'ONSITE'|'REMOTE')=>void;select:(gig:Gig)=>void}) { return <section className="page"><div className="discover-head"><div><p className="eyebrow">GOOD MORNING, ARIA</p><h1>Find work you can <em>vowch</em> for.</h1><p className="lede">Real people. Trusted local gigs. Secure payments.</p></div><div className="trust-score"><Sparkles size={19}/><span><b>780</b> trust score</span><ChevronRight size={16}/></div></div><div className="search-bar"><Search size={19}/><input value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="What kind of help do you need?"/><button>Search</button></div><div className="discover-tools"><div className="filter-pills">{(['ALL','ONSITE','REMOTE'] as const).map((item)=><button className={mode===item?'selected':''} key={item} onClick={()=>setMode(item)}>{item==='ALL'?'All gigs':item==='ONSITE'?'In person':'Remote'}</button>)}</div><span>{gigs.length} trusted gigs nearby</span></div><div className="gig-grid">{gigs.map((gig)=><GigCard key={gig.id} gig={gig} select={select}/>)}</div></section> }
function GigCard({gig,select}:{gig:Gig;select:(gig:Gig)=>void}) { return <article className="gig-card"><div className={`gig-art ${gig.tone}`}><span>{gig.skill}</span><button><HeartHandshake size={18}/></button></div><div className="gig-body"><div className="gig-meta"><span>{gig.mode==='REMOTE'?'Remote':'In person'}</span><small>{gig.posted}</small></div><h3>{gig.title}</h3><p>{gig.description}</p><div className="gig-place"><MapPin size={14}/>{gig.area}</div><div className="gig-footer"><span><b>${gig.budget}</b> fixed</span><button onClick={()=>select(gig)}>View gig <ChevronRight size={15}/></button></div></div></article> }
function PostGig({submit}:{submit:(gig:Gig)=>void}) { const [title,setTitle]=useState(''); const [skill,setSkill]=useState(''); const [budget,setBudget]=useState(''); const [description,setDescription]=useState(''); const [remote,setRemote]=useState(false); const [done,setDone]=useState(false); const handle=(event:React.FormEvent)=>{event.preventDefault();if(!title||!budget)return;const gig={id:`new-${Date.now()}`,title,skill:skill||'General help',budget:Number(budget),description:description||'Details to be shared with trusted applicants.',mode:remote?'REMOTE':'ONSITE' as const,area:remote?'Remote':'Brooklyn, NY',poster:'Aria Rao',vouches:18,posted:'Just now',tone:'mint'};submit(gig);setDone(true)}; return <section className="page form-page"><p className="eyebrow">POST A TRUSTED REQUEST</p><h1>What do you need help with?</h1><p className="lede">Your gig is shared with the Vowch community. Funds stay protected until the work is done.</p><form onSubmit={handle}><label>Gig title<input value={title} onChange={(e)=>setTitle(e.target.value)} placeholder="e.g. Help mounting a shelf" required/></label><div className="form-row"><label>Skill needed<input value={skill} onChange={(e)=>setSkill(e.target.value)} placeholder="Moving help"/></label><label>Budget ($)<input type="number" min="5" value={budget} onChange={(e)=>setBudget(e.target.value)} placeholder="40" required/></label></div><label>Describe the task<textarea value={description} onChange={(e)=>setDescription(e.target.value)} placeholder="What needs doing, when, and any useful details?" rows={5}/></label><button type="button" className={remote?'toggle on':'toggle'} onClick={()=>setRemote(!remote)}><i/> Remote gig</button><button className="primary-submit" type="submit">Post trusted gig <ChevronRight size={17}/></button>{done&&<p className="success"><CheckCircle2 size={17}/> Your gig is live in the community.</p>}</form></section> }
function Jobs({applied,created,select}:{applied:string[];created:Gig[];select:(gig:Gig)=>void}) { const applicationGigs=demoGigs.filter((gig)=>applied.includes(gig.id)); return <section className="page"><p className="eyebrow">YOUR WORKSPACE</p><h1>Your gigs, clearly <em>tracked.</em></h1><div className="job-stats"><article><b>{applicationGigs.length}</b><span>Applications sent</span></article><article><b>{created.length}</b><span>Gigs posted</span></article><article><b>$180</b><span>In protected escrow</span></article></div><div className="jobs-layout"><section className="job-panel"><div className="section-title"><h2>Applications</h2><span>Active</span></div>{applicationGigs.length ? applicationGigs.map((gig)=><div className="job-row" key={gig.id}><div className={`job-icon ${gig.tone}`}><BriefcaseBusiness size={18}/></div><div><b>{gig.title}</b><span>{gig.poster} · Awaiting response</span></div><button onClick={()=>select(gig)}>Track <ChevronRight size={15}/></button></div>):<div className="blank"><BriefcaseBusiness size={27}/><p>Apply to a gig and its progress will appear here.</p></div>}</section><section className="job-panel"><div className="section-title"><h2>Posted by you</h2><span>Manage</span></div>{created.length ? created.map((gig)=><div className="job-row" key={gig.id}><div className="job-icon mint"><Plus size={18}/></div><div><b>{gig.title}</b><span>Open · 0 applications</span></div><button onClick={()=>select(gig)}>View <ChevronRight size={15}/></button></div>):<div className="blank"><Plus size={27}/><p>Post your first request to find trusted help.</p></div>}</section></div></section> }
function Messages(){return <section className="page messages-page"><p className="eyebrow">YOUR INBOX</p><h1>Keep the work moving.</h1><div className="messages"><section>{['Sofia J.','David Chen','Vowch Support'].map((name,index)=><button className={index===0?'chat active':'chat'} key={name}><div className={`avatar ${index===1?'lavender':'coral'}`}>{name.split(' ').map(n=>n[0]).join('')}</div><span><b>{name}</b><small>{index===0?'Thanks — Saturday at 10 works!':index===1?'Miso is looking forward to it.':'Your trust passport is ready.'}</small></span><time>{index===0?'10:42':'Yesterday'}</time></button>)}</section><section className="conversation"><div className="conversation-head"><b>Sofia J.</b><span>● Online</span></div><div className="chat-bubble theirs">Hi Aria! Would Saturday morning work for you?</div><div className="chat-bubble mine">Yes, I can be there at 10. I’ll bring a hand truck.</div><div className="chat-bubble theirs">Perfect. Thanks for being so clear!</div><div className="message-input"><input placeholder="Write a message"/><button><Send size={17}/></button></div></section></div></section>}
function Passport(){return <section className="page passport-page"><p className="eyebrow">YOUR VOWCH PASSPORT</p><h1>Trust that travels with you.</h1><div className="passport-card"><div className="passport-top"><div className="brand-dot">v</div><span>VOWCH PASSPORT<br/><small>VERIFIED MEMBER</small></span><ShieldCheck size={27}/></div><div className="passport-person"><div className="passport-avatar">AR</div><div><h2>Aria Rao</h2><p>Brooklyn Makers · Member since 2025</p></div><b>GOLD</b></div><div className="passport-stats"><span><b>780</b> Trust score</span><span><b>18</b> Vouches</span><span><b>4.9</b> Rating</span></div></div><div className="passport-grid"><article><HeartHandshake/><h3>Vouched by your House</h3><p>Your trust is backed by 18 community connections.</p></article><article><Star/><h3>Skills you’re known for</h3><p>Design, tutoring, organisation, and thoughtful communication.</p></article><article><House/><h3>Brooklyn Makers</h3><p>A House of 24 neighbours who help each other get things done.</p></article></div></section>}
function Wallet(){return <section className="page wallet-page"><p className="eyebrow">PAYMENTS & ESCROW</p><h1>Your work, paid <em>fairly.</em></h1><div className="balance-card"><span>AVAILABLE BALANCE</span><b>$128.50</b><p>Protected by Vowch escrow</p><button>Withdraw funds <ChevronRight size={16}/></button></div><section className="transactions"><div className="section-title"><h2>Recent activity</h2><span>View all</span></div>{[['Dog walking','+$25.00','Completed'],['Moving help','−$40.00','In escrow'],['Trust bonus','+$5.00','Reward']].map(([name,amount,status],i)=><div className="transaction" key={name}><div className={`job-icon ${['mint','peach','gold'][i]}`}><CircleDollarSign size={18}/></div><div><b>{name}</b><span>{status}</span></div><strong className={amount.startsWith('+')?'plus':''}>{amount}</strong></div>)}</section></section>}
function GigModal({gig,applied,close,apply}:{gig:Gig;applied:boolean;close:()=>void;apply:()=>void}){return <div className="modal-backdrop" onMouseDown={close}><article className="gig-modal" onMouseDown={(e)=>e.stopPropagation()}><button className="close" onClick={close}><X size={20}/></button><div className={`modal-art ${gig.tone}`}><span>{gig.skill}</span></div><p className="eyebrow">{gig.mode==='REMOTE'?'REMOTE GIG':'IN-PERSON GIG'} · {gig.posted}</p><h2>{gig.title}</h2><p>{gig.description}</p><div className="modal-details"><span><MapPin size={16}/>{gig.area}</span><span><HeartHandshake size={16}/>{gig.poster} · {gig.vouches} vouches</span></div><div className="modal-footer"><b>${gig.budget} <small>fixed budget</small></b><button disabled={applied} onClick={apply}>{applied?'Application sent':'Apply to help'} <ChevronRight size={16}/></button></div></article></div>}
createRoot(document.getElementById('root')!).render(<App/>);
